services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - .:/srv
    restart: unless-stopped

# username : admin
# password : admin
# access by http://localhost:8080
