services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "your_password1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
