services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "your_password1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

# Host:       localhost
# Port:       1433
# Database:   master (or your database)
# Username:	  sa
# Password: 	your_password1234

# jdbc:sqlserver://localhost:1433;databaseName=your_database;user=sa;password=your_password1234;
